### PR TITLE
Google service

### PR DESCRIPTION
**Pull request by gmackay**
The google option.

Uses the google Java API which is rather neat.

Could also look into using Rest Template as this will be needed for other services.

### CODE REVIEW

**Comment by reachsaurabh** [comment]
@gmackay @seamussingh Hi Gordon , Looks I have merged your PR incorrectly , please raise your PR for feature branches to develop only , I missed too .

**Comment by reachsaurabh** [comment]
Closed

**Comment by gmackay** [comment]
Oops, i see what happened.  Sorry about that!

Will try harder in future :)


Thanks,

**Comment by reachsaurabh** [comment]
No issue mate , lets get google service into develop and leave the branches as is we are not going to delete the prototype branch for now .
Cheers.

**Pull request closed without merging**
